### ISSUE TITLE
negative fetch size is mysql-specific

### ISSUE THREAD

**Issue by drmirror** [johnlpage/MongoSyphon#11]
I used MongoSyphon against SQL Server at a customer, and it turns out that setting the fetch size to a negative value, as in line 92 in RDBMSConnection.java, is a feature specific to the MySQL driver. It didn't work with the MSSQL 6.2.1 driver and I had to comment out that line, after which things seemed to be okay. But I don't know the full implications of that.

Discussion on stackoverflow: https://stackoverflow.com/questions/25019410/confusion-with-setfetchsize-method-of-statement-object

Link to the place in the code: https://github.com/johnlpage/MongoSyphon/blob/a66484c875b244c8e03ec0816fe7f22fe5e3295c/src/main/java/com/johnlpage/mongosyphon/RDBMSConnection.java#L92

**Comment by johnlpage** [comment]
Hi, someone had the same issue with oracle.
The implication is you need to find a way to avoid it pulling the whole
result set for a large set. Will set that as mysql only though.

**Comment by johnlpage** [comment]
Fixed - that only kicks in for MySQL now.
